@host = http://localhost:5237

### All auctions
GET {{host}}/auctions

### One auction
GET {{host}}/auctions/2

### Auction that does not exist -> 404
GET {{host}}/auctions/999

### Create an auction -> 201
POST {{host}}/auctions
Content-Type: application/json

{
  "itemName": "Nintendo Switch",
  "startingPrice": 1000
}

### Bid that is too low -> 400
POST {{host}}/auctions/2/bids
Content-Type: application/json

{
  "bidderName": "Ada",
  "amount": 900
}

### Valid bid -> 200
POST {{host}}/auctions/2/bids
Content-Type: application/json

{
  "bidderName": "Ada",
  "amount": 1200
}

### Close an auction -> 200
PATCH {{host}}/auctions/2
Content-Type: application/json

{
  "isClosed": true
}

### Bid on a closed auction -> 400
POST {{host}}/auctions/2/bids
Content-Type: application/json

{
  "bidderName": "Linus",
  "amount": 5000
}

### Active auctions only
GET {{host}}/auctions?active=true

### Delete an auction -> 204
DELETE {{host}}/auctions/5

### Delete the same one again -> 404
DELETE {{host}}/auctions/5
